config/routes.rb
Intranet::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "user_sessions"}

  match "overview/list", :to => "overview#list"
  match "dashboard", :to => "overview#dashboard", :as => :dashboard

  resources :employees

  # Despert
  # ================================================================
  resources :groups
  resources :comments, :only => :destroy

  resources :project_types

  resources :projects, :only => :index
  resources :projects, :path => "", :except => :index do
    collection do
      get :list
    end

    resources :attachments

    resources :messages do
      collection do
        get :list
      end
    end

    resources :milestones do
      member do
        get :toggle
      end
    end

    resources :task_lists do
      resources :tasks, :only => :create

      collection do
        post :reorder_task
      end

      member do
        post :toggle_archive
        get :completed_tasks
      end
    end

    resources :tasks do
      member do
        get :toggle
        get :archive_toggle
        get :list_events
      end
    end
  end

  resources :tasks, :only => :none do
    resources :comments, :only => :create
  end

  resources :milestones, :only => :none do
    resources :comments, :only => :create

    collection do
      get :overview
    end
  end

  resources :messages, :only => :none do
    resources :comments, :only => :create
  end


  root :to => "overview#index"
end

app/models/task.rb
class Task < ActiveRecord::Base
  fire_events :background => :project, :context => :project, :except => :update

  belongs_to :task_list
  belongs_to :employee
  belongs_to :author, :class_name => 'Employee'

  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :events, :as => :subject, :dependent => :destroy
  has_many :events_as_context, :class_name => 'Event', :as => :context
  delegate :project, :to => :task_list

  validates :title, :presence => true, :length => { :maximum => 80 }
  validates :position, :presence => true, :numericality => true, :allow_nil => false
  validate :unique_title

  validates_presence_of :author
  validates_presence_of :task_list
  validates_presence_of :duration

  validates_presence_of :employee, :if => :completed?
  validates :duration, :numericality => {:greater_than => 0}, :if => :completed?

  scope :active, where(:closed => false)
  scope :closed, where(:closed => true)
  scope :completed, active.where("completed_at IS NOT NULL")
  scope :uncompleted, active.where("completed_at IS NULL")
  scope :completed_between, lambda { |date_ini, date_end| active.where(:completed_at => date_ini.to_time.in_time_zone('UTC')..date_end.to_time.in_time_zone('UTC')) }
  scope :latest_completed, active.completed.order("completed_at DESC")
  scope :latest_uncompleted, active.uncompleted.order("updated_at DESC")
  scope :planned, uncompleted.joins(:task_list => :milestone).order("finishes_at ASC, position ASC, tasks.updated_at DESC")
  scope :unplanned, latest_uncompleted.joins(:task_list).where(:task_lists => {:milestone_id => nil})

  before_save :set_old_employee_id
  after_save :notify_assigned_employee

  def to_s
    title
  end

  def toggle
    unless completed?
      self.completed_at = Time.now
      self.position = 0
      generate_event(:event_type => "completed", :subdescrip => "Tasca completada")
    else
      max = task_list.tasks.uncompleted.maximum('position') || 0
      self.completed_at = nil
      self.position = max + 1
      generate_event(:event_type => "reopened", :subdescrip => "Tasca reoberta")
    end
  end

  def archive_toggle
    if closed
      self.closed = false
      generate_event(:event_type => "archived", :subdescrip => "Tasca desarxivada")
    else
      self.closed = true
      generate_event(:event_type => "unarchived", :subdescrip => "Tasca arxivada")
    end
  end

  def edit_content(params)
    self.title = params[:task][:title]
    self.description = params[:task][:description]
    generate_event(:event_type => "modified") if (title_changed? || description_changed?)
  end

  def reassign_user(params)
    self.employee_id = params[:task][:employee_id]
    generate_event(:event_type => "reassigned_user", :subdescrip => "Tasca assignada a #{employee}") if employee_id_changed?
  end

  def add_hours(params)
    self.duration = params[:task][:duration]
    generate_event(:event_type => "add_hours", :subdescrip => "Hores modificades: #{duration_was} -> #{duration}") if duration_changed?
  end

  def completed?
    completed_at.present?
  end

  def move_to(tl, task)
    self.task_list = tl
    # task is the previous task in order, we must put ourself after it
    if task
      tl.increment_positions_from(task.position)
      self.position = task.position + 1
    else
      self.position = tl.tasks.minimum(:position) - 1
    end

    if valid?
      if task_list_id_was == tl.id
        if tl.tasks.minimum(:position) - 1 == position
          text = "La tasca ara és la més important de #{tl}"
        else
          text = "Tasca canviada de prioritat"
        end
        generate_event(:event_type => "sorted", :subdescrip => text)
      else
        generate_event(:event_type => "moved", :subdescrip => "Tasca moguda a la llista #{task_list}")
      end
    end
  end

  def new_comment(comment)
    recipients = Comment.notification_recipients_for(comments, comment)
    recipients << employee if employee && !recipients.include?(employee) && comment.user != employee

    recipients.each do |x|
      Delayed::Job.enqueue NotifierMailerJob.new(:new_comment, x, comment)
    end
  end

private
  def unique_title
    errors[:title] << " ha de ser unic a la llista de tasques" if task_list.tasks.where(:title => title).count == 1 and new_record?
  end

  def set_old_employee_id
    # We need to enqueue a job with a real self.id, so it must be performed on
    # after_save. But, to check if employee_id was changed we need to keep
    # this information!
    @employee_id_was = employee_id_was
  end

  def notify_assigned_employee
    if employee_id != @employee_id_was && employee_id != author_id
      #NotifierMailer.assigned_in_a_task(employee, self).deliver
      Delayed::Job.enqueue NotifierMailerJob.new(:assigned_in_a_task, employee, self)
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_resource :project, :find_by => :ref, :except => [:archive_toggle, :toggle_task]
  authorize_resource :project
  layout 'project'

  def show
    @task = Task.find(params[:id])
    authorize! :read, @task
    @events = @task.events.paginate(:per_page => 20, :page => params[:page])
    respond_to do |format|
      format.html
      format.js { render :json => @task.to_json }
    end
  end

  def toggle
    @task = Task.find(params[:id])
    authorize! :toggle_task, @task

    @task.toggle

    respond_to do |format|
      if @task.save
        flash[:notice] = "Tasca completada amb èxit"
        format.html { redirect_to request.env["HTTP_REFERER"] || project_task_lists_url(@task.project) }
        format.js
      else
        flash[:notice] = @task.errors.full_messages
        format.html { redirect_to request.env["HTTP_REFERER"] || project_task_lists_url(@task.project) }
        format.js
      end
    end
  end

  def archive_toggle
    @task = Task.find(params[:id])
    authorize! :archive_toggle_task, @task

    @task.archive_toggle

    respond_to do |format|
      if @task.save
        flash[:notice] = "Tasca #{@task.closed ? 'arxivada' : 'desarxivada'} amb èxit"
        format.html { redirect_to request.env["HTTP_REFERER"] || project_task_lists_url(@task.project) }
        format.js
      else
        flash[:notice] = @task.errors.full_messages
        format.html { redirect_to request.env["HTTP_REFERER"] || project_task_lists_url(@task.project) }
        format.js
      end
    end
  end

  def create
    @task_list = TaskList.find(params[:task_list_id])

    v = params[:task].keys.first
    @task = @task_list.tasks.build params[:task].fetch(v)
    authorize! :create, @task

    @task.position = (@task_list.tasks.uncompleted.maximum('position') || 0) + 1
    @task.author = current_user

    @task.toggle if params[:commit] == "Publicar completada"

    respond_to do |format|
      if @task.save
        format.html {
          flash[:notice] = "Tasca creada amb èxit."
          redirect_to @task_list
        }
        format.js
      else
        format.html { render :action => "new" }
        format.js
      end
    end
  end

  def new
    render :layout => 'no-layout'
  end

  def edit
    @task = Task.find(params[:id])
    authorize! :update, @task
    @task_list = @task.task_list
    render :layout => 'no-layout'
  end

  def update
    @task = Task.find(params[:id])
    authorize! :update, @task

    if params[:task][:title].present? || params[:task][:description].present?
      authorize! :edit_task_content, @task
      @task.edit_content(params)
    end
    if params[:task][:employee_id].present?
      authorize! :reassign_user, @task
      @task.reassign_user(params)
    end
    if params[:task][:duration].present?
      authorize! :add_hours, @task
      @task.add_hours(params)
    end
    @task_list = @task.task_list

    if params[:commit] == "Publicar completada"
      authorize! :toggle_task, @task
      @task.toggle
    end

    respond_to do |format|
      if @task.save
        flash[:notice] = "Tasca actualitzada existosament."
        format.html { redirect_to request.env["HTTP_REFERER"] || project_task_lists_url(@task.project) }
        format.js  { head :ok }
      else
        flash[:alert] = "Error a l'actualitzar la tasca"
        format.html { redirect_to request.env["HTTP_REFERER"] || project_task_lists_url(@task.project) }
        format.js  { render :json => @task.errors.to_json, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    authorize! :destroy, @task

    @task_list = @task.task_list
    @task.destroy

    respond_to do |format|
      format.html {redirect_to request.env["HTTP_REFERER"] || project_task_lists_url(@task_list.project)}
      format.js
    end
  end
end

app/views/tasks/_form.html.haml
- uid = f.object.new_record? ? "new" : f.object.id.to_s
.task-form
  .user-selector
    - if f.object.new_record? || can?(:reassign_user, f.object)
      - @project.employees.each_with_index do |user, i|
        - user == f.object.employee ? seluser = "selected" : seluser = ""
        = link_to gravatar_for(user, :size => 30), "#", :tabindex => i + 3, :OnClick => "return false;", :class => "task_user_input_#{task_list.id}_#{uid} #{seluser}", :"data-id" => user.id, :title => user.to_s
      = f.hidden_field :employee_id, :id => "task_user_id_#{task_list.id}_#{uid}"
    .responsible
      = image_tag("responsible.png")
      %span{:id => "task_user_display_#{task_list.id}_#{uid}"}= f.object.employee.presence

  - disabled = ( f.object.new_record? || can?(:edit_task_content, f.object) ) ? false : true
  .title-input= f.text_field :title, :class => 'text_field', :maxlength => 80, :placeholder => "Títol de la tasca", :tabindex => 1, :disabled => disabled, :id => "task_title_#{task_list.id}_#{uid}"

  .clearboth
  .time-selector
    %h3 Temps dedicat
    - duration_tab_order = 2
    - if f.object.new_record? || can?(:add_hours, f.object)
      - duration_tab_order += @project.employees.size
      = f.text_field :duration, :id => "task_duration_#{task_list.id}_#{uid}", :tabindex => duration_tab_order, :class => "task_duration_input"
    .time-icon= image_tag("watch.png")

  - disabled = ( f.object.new_record? || can?(:edit_task_content, f.object) ) ? false : true
  .description-input
    = f.text_area :description, :placeholder => "Descripció de la tasca", :tabindex => 2, :disabled => disabled, :id => "task_description_#{task_list.id}_#{uid}"
    %p Autor: #{f.object.author || current_user}

  .clearboth.separator
  .submit-task-form
    = f.submit "Publicar", :id => "task_list_#{task_list.id}_#{uid}_submit", :tabindex => duration_tab_order + 1
    = f.submit "Publicar completada", :id => "task_list_#{task_list.id}_#{uid}_submit_and_close", :tabindex => duration_tab_order + 2


- content_for :custom_js do
  :javascript
    /* User selector */
    $(".task_user_input_#{task_list.id}_#{uid}").click(function() {
      $("#task_user_id_#{task_list.id}_#{uid}").val($(this).attr("data-id"));
      $("#task_user_display_#{task_list.id}_#{uid}").html($(this).attr("title"));
      $(".selected").removeClass("selected");
      $(this).addClass("selected");
    });
    /* Time tracking */
    $(".task_duration_input").live("click", function() {
      $(this).select();
    });

app/views/tasks/_task.html.haml
.task-item{:data_task => task.id, :id => "task_item_#{task.id}", :"data-task_list_id" => task.task_list.id}
  - if ["tasks", "task_lists", "milestones", "overview"].include?(controller_name)
    .position{:id => "task_position_#{task.id}"}
      - if task.completed_at.blank?
        - if defined? task_counter
          = task_counter + 1
        - else
          = task.position
      - else
        = "-"
    .action-label
      - if can? :toggle_task, task
        - if task.completed_at.blank?
          = link_to image_tag("checked.png"), toggle_project_task_path(task.project, task), :remote => true, :class => "button"
        - else
          = link_to image_tag("reopen.png"), toggle_project_task_path(task.project, task), :remote => true, :class => "button"
      - else
        &nbsp;
  .completion-date
    - unless task.completed_at.blank?
      = pretty_date task.completed_at
    - else
      = pretty_date task.updated_at
  .task-title
    = link_to(task.title[0..70], [task.project, task])
    - unless ["task_lists", "tasks", "milestones"].include?(controller_name)
      = project_link(task.project)
  .task-comments
    .comment-globe= task.comments.size.to_s if task.comments
  .task-buttons{:id => "task_buttons_#{task.id}"}
    - if can? :update, task
      .button{:id => "task-edit-#{task.id}"}= link_to image_tag("editicon.png"), edit_project_task_path(task.project, task), :rel => "facebox"
    - if can? :destroy, task
      = link_to image_tag("deleteicon.png"), [task.project, task], :method => :delete, :remote => true, :confirm => 'Segur?', :class => "button"
  .gravatar
    = raw task.employee ? gravatar_for(task.employee, :size => 40, :title => "Responsable") : "&nbsp;"
    .author= raw task.author ? gravatar_for(task.author, :size => 40, :title => "Autor") : "&nbsp;"
  .duration
    = task.duration
-#.clearboth

app/views/tasks/create.js.erb
<% if @task.errors.any? %>
    $("<span><%= escape_javascript(@task.errors.full_messages.join("\n")) %></span>").purr();

<% elsif !@task.completed? %>

  var last_index = $("#task_list_uncompleted_<%=@task.task_list.id.to_s%>").children(".task-item").last().children(".position").html();

  $("#task_list_uncompleted_<%=@task.task_list.id.to_s%>").append("<%= raw escape_javascript(render @task, :task_list => @task_list) %>").fadeIn("slow");
  $("#task_list_<%= @task.task_list.id %>_add_text").fadeIn("slow");
  $(".text_field").val("");
  $("textarea[id*='_description']").val("");
  $("span[id*='time_tracking_total_']").html("");
  $("span[id*='task_user_display_']").html("");
  $("input[id*='task_duration_']").val(0.0);
  $(".selected").removeClass("selected");
  $(".text_field")[0].focus();

  $('a[rel*=facebox]').facebox();

  if (isNaN(parseInt(last_index))) {
    last_index = 0;
  }
  $('#task_position_<%= @task.id %>').html(parseInt(last_index)+1);
<% else %>
  $(".text_field").val("");
  $("textarea[id*='_description']").val("");
  $("span[id*='time_tracking_total_']").html("");
  $("span[id*='task_user_display_']").html("");
  $("input[id*='task_duration_']").val(0.0);
  $(".selected").removeClass("selected");

  var last_index = $("#comptasks_<%= @task.task_list.id %>").html();
  $("#comptasks_<%= @task.task_list.id %>").html(parseInt(last_index)+1);

  $("<span>Tasca creada i completada</span>").purr();
<% end %>

app/views/tasks/destroy.js.erb
$('#task_item_<%= @task.id %>').nextAll().children(".position").html(function(index, oldhtml) {
  var html = parseInt(oldhtml) - 1;
  return html;
});

$('#task_item_<%= @task.id %>').fadeOut('slow', function () {
  $(this).remove();
});

app/views/tasks/edit.html.haml
%h1 Modifica la tasca
= form_for [@project, @task], :html => { :class => :form } do |f|
  = render "form", :f => f, :task_list => @task_list

app/views/tasks/new.html.haml
- title "Nova tasca"
%h1 Modifica la tasca
= form_for [@project, Task.new], :html => { :class => :form } do |f|
  = render "shared/error_messages", :target => @task
  = render :partial => "form", :locals => {:f => f, :task_list => @task_list}

app/views/tasks/show.html.haml
- title "Tasca " + @task.title

.task-show
  %h1 Detalls de la tasca
  .task-body
    .action-buttons
      - if @task.closed
        = link_to image_tag("archive.png"), archive_toggle_project_task_path(@project, @task), :class => "button"
      - else
        = link_to image_tag("emptyfolder.png"), archive_toggle_project_task_path(@project, @task), :class => "button"
      = link_to image_tag("editicon.png"), edit_project_task_path(@task.project, @task), :rel => "facebox", :class => "button"
      = link_to image_tag("deleteicon.png"), project_task_path(@task.project, @task), :confirm => 'Segur?', :method => :delete, :class => "button"
    %h2
      = @task.title
      = " [ARXIVADA #{pretty_date @task.updated_at}]" if @task.closed

    .clearboth
    .right= raw gravatar_for(@task.employee, :size => 175) if @task.employee

    %table
      %tr
        %td Llista
        %td
          = link_to @task.task_list.name, [@task.project, @task.task_list]
          (#{@task.task_list.group.presence})
      %tr
        %td= image_tag("responsible.png")
        %td
          - if can? :reassign_user, @task
            - employees = @project.employees.collect{ |e| [e.id, e.name.gsub(/['"]/, '')] }
            = best_in_place @task, :employee_id, :type => :select, :path => [@task.project, @task], :collection => employees
        -# %td= @task.employee.presence
      %tr
        %td= image_tag("watch.png")
        %td
          - if can? :update, @task
            = best_in_place @task, :duration, :nil => 0, :path => [@task.project, @task]
          - else
            = @task.duration || "0"
          hores
      %tr
        %td Estat
        %td
          - if @task.completed_at
            %span{:style => "color:green"} Finalitzada
            (#{link_to "reobrir", toggle_project_task_path(@project, @task)})
          - else
            %span{:style => "color:red"} Pendent
            (#{link_to "completar", toggle_project_task_path(@project, @task)})

    %h3 Descripció
    = markdown(@task.description)

  = render :partial => 'comments/comments_block', :locals => {:referer => @task }

  .separator
  %hr
  %h2 Historial de la tasca
  .show-history
    %table
      - @events.each do |event|
        %tr
          %td= event.subdescrip
          %td= pretty_date event.created_at
          %td per #{event.actor.name}

  = will_paginate @events, :previous_label => "&laquo; Anterior", :next_label => "Següent &raquo;"

app/views/tasks/toggle.js.erb
$("#contentbox").find(".notice").remove();
<% unless @task.errors.any? %>
  <% if !@task.completed_at.nil? %>
    $('#task_item_<%= @task.id %>').nextAll().children(".position").html(function(index, oldhtml) {
      var html = parseInt(oldhtml) - 1;
      return html;
    });
    $("#task_item_<%= @task.id %>").fadeOut().remove();
    $("#task_list_completed_<%= @task.task_list.id %>").prepend("<%= escape_javascript(render(@task, :task_list => @task_list)) %>").fadeIn().effect("highlight", {}, 3000);
    $('#comptasks_<%= @task.task_list.id %>').html(function(index, oldhtml) {
      var html = parseInt(oldhtml) + 1;
      return html;
    });
  <% else %>
    $("#task_item_<%= @task.id %>").fadeOut().remove();
  $("#task_list_uncompleted_<%= @task.task_list.id %>").append("<%= escape_javascript(render(@task, :task_list => @task_list)) %>").fadeIn().effect("highlight", {}, 3000);
    $('#task_item_<%= @task.id %>').children(".position").html(<%= (@task.position - 1).to_s %>);
    $('#comptasks_<%= @task.task_list.id %>').html(function(index, oldhtml) {
      var html = parseInt(oldhtml) - 1;
      return html;
    });
  <% end %>
<% else %>
    $("<span><%= escape_javascript @task.errors.full_messages.join("\n") %></span>").purr();
<% end %>