config/routes.rb
Intranet::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "user_sessions"}

  match "overview/list", :to => "overview#list"
  match "dashboard", :to => "overview#dashboard", :as => :dashboard

  resources :employees

  # Despert
  # ================================================================
  resources :groups
  resources :comments, :only => :destroy

  resources :project_types

  resources :projects, :only => :index
  resources :projects, :path => "", :except => :index do
    collection do
      get :list
    end

    resources :attachments

    resources :messages do
      collection do
        get :list
      end
    end

    resources :milestones do
      member do
        get :toggle
      end
    end

    resources :task_lists do
      resources :tasks, :only => :create

      collection do
        post :reorder_task
      end

      member do
        post :toggle_archive
        get :completed_tasks
      end
    end

    resources :tasks do
      member do
        get :toggle
        get :archive_toggle
        get :list_events
      end
    end
  end

  resources :tasks, :only => :none do
    resources :comments, :only => :create
  end

  resources :milestones, :only => :none do
    resources :comments, :only => :create

    collection do
      get :overview
    end
  end

  resources :messages, :only => :none do
    resources :comments, :only => :create
  end


  root :to => "overview#index"
end

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  #errorExplanation
    %h2
      = pluralize(target.errors.count, "error")
      prohibited this record from being saved:
    %ul
      - target.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feeds.html.haml
#events
  - if @events
    %h2 Activitat
    - @events.each do |subject, events|
      - proj = subject.respond_to?(:project) ? subject.project : nil
      - proj = subject if subject.is_a? Project
      - author = events.first.actor
      - color = "#FFF"
      - if author && author.is_a?(Employee) && author.group
        - color = soft_color author.group.color
      .event{:style => "background-color:##{color}", :id => "event-#{subject.id}"}
        - if proj
          .right= project_link proj

        - if subject.is_a?(Project) || proj
          %h3
            = link_to "#{t subject.class}: #{subject}", subject.is_a?(Project) ? subject : [proj, subject]
            %span= " (Última activitat #{pretty_date events.last.created_at})"

        .item-list{:id => "subject-#{subject.id}"}
          = render :partial => 'events/event', :collection => events
        - if subject.respond_to?(:comments)
          = render :partial => 'comments/form', :locals => {:referer  => subject}

app/views/shared/_footer.html.haml
#footer
  .container{:style => "z-index: 1;"}
    .span-8.first
      %h3= t('news_feed')
      %ul.news_list
        %li Post al blog
        %li
          Post al blog II (2 #{"#{t('comment')}s"})
        %li Post al blog III
        - ##for post in @posts
          %li
    .span-7
      %h3= t('talktous')
      %p= t('talktous_text')
      %h3= t('follow_us')
      %a{:href => "#", :title => "RSS Feeds"}
        %img.share_footer{:alt => "RSS logo", :src => "/images/rss.png"}/
      %a{:href => "https://twitter.com/itnig", :title => "Twitter Account"}
        %img.share_footer{:alt => "Twitter logo", :src => "/images/twitter.png"}/
      %a{:href => "http://www.facebook.com/pages/Itnig/302506280728?ref=search&sid=1245973310.2482837461..1", :title => "Facebook Webpage"}
        %img.share_footer{:alt => "Facebook logo", :src => "/images/facebook.png"}/
    #footer_background_right
      %img{:src => "/images/background_footer.png"}/
    .span-8.last
      %h3= t('aboutus')
      %p= t('aboutus_text')

app/views/shared/_header.html.haml
#header
  = render 'shared/menu'

app/views/shared/_menu.html.haml
%nav
  %ul
    %li
      = link_to 'Vista general', root_path, :class => controller.controller_name == "overview" && controller.action_name == "index" ? "current" : ""
    %li
      = link_to 'Taulell', dashboard_path, :class => controller.controller_name == "overview" && controller.action_name == "dashboard" ? "current" : ""
    %li
      = link_to 'Projectes', projects_path, :class => controller.controller_name == "projects" ? "current" : ""
    %li
      = link_to "Grups", groups_path, :class => controller.controller_name == "groups" ? "current" : ""

    - if can? :read, Employee
      %li
        = link_to 'Usuaris', employees_path, :class => controller.controller_name == "employees" ? "current" : ""

app/views/shared/_preheader.html.haml
-# preheader classes can be { employee , accountable , administrative, collaborator }
#preheader{:class => "#{current_user.role.presence}"}
  .right
    %ul#project-menu
      %li.current
        %a{:href => "#"} Accés ràpid a projectes
        %ul
          - @projs = current_user.admin? ? Project.running.recent : current_user.projects.recent
          - @projs.each do |p|
            %li
              = link_to_if(@project != p, "#" + p.ref, project_task_lists_path(p)) {"<span id='current'>##{p.ref}</span>"}

  .upper-title
    = link_to "ITNIG INTRANET", root_url
    - if can? :read, :status
      = link_to "(status)", "/status"
  #user-menu
    = link_to "Home", root_path
    |
    = link_to current_user, current_user
    (#{current_user.role})
    |
    = link_to "Sortir", destroy_user_session_path

app/views/shared/_project-menu.html.haml
#project-title{:style => "background-color: #{@project.to_color}"}
  %h2
    = @project.name
    [#{@project.get_status}]
    = "- #{resume_text(@project.status_description, 75)}" unless @project.status_description.blank?

  .right
    - if can? :update, @project
      = link_to image_tag("editicon.png"), edit_project_url(@project)

  Project Manager:
  %b #{@project.manager.to_s}
  |
  Hores de treball:
  %b #{@project.total_hours} h
  - if @project.variable?
    | ROI / mes:
    %b= number_to_currency @project.variable_part


#project-menu
  %nav
    %ul
      %li
        = link_to "Principal", @project
      %li
        = link_to "Tasques", project_task_lists_path(@project)
      %li
        = link_to "Milestones", project_milestones_path(@project)
      %li
        = link_to "Missatges", project_messages_path(@project)
      %li
        = link_to "Documents", project_attachments_path(@project)

app/views/shared/cancan_rescue_from_js.js.erb
$("<span>Accés no autoritzat</span>").purr();