config/routes.rb
Intranet::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "user_sessions"}

  match "overview/list", :to => "overview#list"
  match "dashboard", :to => "overview#dashboard", :as => :dashboard

  resources :employees

  # Despert
  # ================================================================
  resources :groups
  resources :comments, :only => :destroy

  resources :project_types

  resources :projects, :only => :index
  resources :projects, :path => "", :except => :index do
    collection do
      get :list
    end

    resources :attachments

    resources :messages do
      collection do
        get :list
      end
    end

    resources :milestones do
      member do
        get :toggle
      end
    end

    resources :task_lists do
      resources :tasks, :only => :create

      collection do
        post :reorder_task
      end

      member do
        post :toggle_archive
        get :completed_tasks
      end
    end

    resources :tasks do
      member do
        get :toggle
        get :archive_toggle
        get :list_events
      end
    end
  end

  resources :tasks, :only => :none do
    resources :comments, :only => :create
  end

  resources :milestones, :only => :none do
    resources :comments, :only => :create

    collection do
      get :overview
    end
  end

  resources :messages, :only => :none do
    resources :comments, :only => :create
  end


  root :to => "overview#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  include Intranet::DateFormat
  has_paper_trail :only => [:status_description]

  fire_events :background => :self, :context => :self, :except => :update

  STATUS_LIST = [[0, "Queued"], [1, "Working"], [2, "Priority"], [3, "Urgent"]]
  STATES_LIST = ["running", "halted", "closed"]

  belongs_to :project_type
  belongs_to :manager, :class_name => 'Employee'

  has_many :memberships
  has_many :employees, :through => :memberships

  has_many :events, :as => :subject, :dependent => :destroy
  has_many :events_as_background, :class_name => 'Event', :as => :background, :include => [ :background, :subject, :context, :actor ]

  has_many :milestones, :dependent => :destroy
  has_many :messages, :dependent => :destroy
  has_many :task_lists, :dependent => :destroy
  has_many :tasks, :through => :task_lists
  has_many :attachments, :dependent => :destroy

  validates_presence_of :project_type
  validates :ref,
      :presence => true,
      :uniqueness => true,
      :length => {:in => 4..15}

  validates :manager, :presence => true

  validates :employees, :presence => true
  validates_presence_of :starting_date
  validate :pm_is_an_employee

  default_scope order('status DESC', 'updated_at DESC')

  scope :running, where(:state => "running")
  scope :recent, lambda { |*period| where("updated_at > ?", (Date.today - (period.first || 15.days)).to_time.in_time_zone('UTC')) }
  scope :started_between, lambda { |date_ini, date_end| where(:starting_date => date_ini.to_time.in_time_zone('UTC')..date_end.to_time.in_time_zone('UTC')) }

  before_validation :downcaize_ref
  before_create :create_unassigned_task_list
  before_update :launch_events

  def get_ref
    "##{ref}"
  end

  def get_status
    Hash[STATUS_LIST][status]
  end

  def calculate_total_hours
    task_lists.map{|x| x.total_hours}.sum
  end

  def completed_hours
    task_lists.map{|x| x.completed_hours}.sum
  end

  def last_tasks(fromdate)
    i = 19
    last_hours = []
    while i >= 0
      last_hours << [fromdate - i, self.tasks.where("date(completed_at) = ?", fromdate - i).sum('duration')]
      i = i - 1
    end
    return last_hours
  end

  def get_events
    events_as_background
  end

  def to_s
    name
  end

  def create_unassigned_task_list
    self.task_lists.build(:name => "unassigned")
  end

  def to_color
    "##{project_type.color}" || "#EEE" unless project_type.blank?
  end

  def starting_date=(value)
    self[:starting_date] = format_input_date(value)
  end

  def to_param
    self[:ref]
  end

  def ref
    self[:ref].upcase
  end

private
  def downcaize_ref
    self.ref.gsub!(/[^A-Za-z]/, "")
    self.ref.downcase!
  end

  def pm_is_an_employee
    errors.add(:manager, "must participate in this project") unless employees.include?(manager)
  end

  def launch_events
    if status_description_was != status_description
      generate_event(:event_type => "status_update", :subdescrip => "Status canvia de \"#{status_description_was}\" a \"#{status_description}\"")
    end
  end
end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
  has_many :projects

  validates_presence_of :name

  def to_s
    name
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_resource :find_by => :ref, :except => [:list, :list_events, :show]
  authorize_resource
  layout 'project', :except => [:index, :new]

  EVENTS_PER_PAGE = 25 # how many events of a project are displayed

  def activate
    @project.activate!
    redirect_to projects_path
  end

  def show
    @project = Project.includes(:tasks).find_by_ref! params[:id]
    authorize! :read, @project

    #@date = params[:date] ? params[:date].to_date : Date.today
    #@date = @date < Date.today ? @date : Date.today # Que no es passi
    #@last_tasks = @project.last_tasks(@date)

    @events = @project.get_events.limit(100)
    @events = Event.prepare_for_view(@events)

    respond_to do |format|
      format.html
      format.xml { render :xml => @project }
    end
  end

  def new
    respond_to do |format|
      format.html { render :layout => "application" }
      format.xml  { render :xml => @project }
    end
  end

  def create
    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => "El projecte s'ha creat amb èxit") }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => :new, :layout => "application" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def index
    @projects = current_user.admin? ? Project.all : current_user.projects
    @projects = @projects.paginate(:per_page => 30, :page => params[:page])

    render :layout => "application"
  end

  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => "El projecte s'ha actualitzat amb èxit") }
        format.json {head :ok}
      else
        format.html { render :action => :edit }
        format.json { render :status => :unprocessable_entity, :nothing => true}
      end
    end
  end

  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end

  def contract
    @lang = params[:lang]
    @client = @project.client
    respond_to do |format|
      format.html { render :layout => "pageable" }
      format.pdf { render :pdf => "Document #{@client.name}", :encoding => "utf-8" }
    end
  end

  def get_roi
    @project = Project.find_by_ref! params[:id]
    authorize! :get_roi, @project

    respond_to do |format|
      begin
        init_date = params[:init_date]
        end_date = params[:end_date]
        @info = @project.get_variable_retribution(init_date, end_date)

        format.js
      rescue
        format.js { render :status => :unprocessable_entity, :nothing => true }
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_link(project, opts = {})
    default_opts = {:label => :name}
    opts = default_opts.merge(opts)
    link_to opts[:label] == :name ? project : project.ref, project_task_lists_path(project), :class => "project-label", :style => "background-color:#{project.to_color}"
  end
end

app/views/projects/_contract_ca.html.haml
- I18n.locale = "ca"
.page.shadow
  %div{:style => "height:20em;"}
  %div{:style => "margin-left:2em"}
    %h1
      Document #{@project}
    %h2.right{:style => "margin-right:5em"} Pla Bàsic
  %div{:style => "height:20em;"}
  %div{:style => "font-size:1.3em;margin-left:3em;"}
    %p
      Itnig Solutions, S.L.
      %br/
    %p
      Barcelona, #{l @project.starting_date, :format => :long}
.page.shadow
  .headnote
    %div{:style => "float:right"}> 1
    Projecte #{@project}
  %h2 Descripció Document
  %p Aquest document presenta a nivell general la descripció del producte ofert i una guia de desenvolupament tant per Itnig com pel client.
  %p En primer lloc es descriu les característiques generals del producte. S’explica la tecnologia usada per implementar les funcionalitats requerides i es detalla cadascuna d’aquestes funcionalitats a nivell descriptiu. Es separen les diferents fases d’implementació de l’aplicació web. S’expliquen les característiques dels servidors on s’allotjarà l’aplicació. S’especiﬁca els serveis adjunts al producte a part del propi desenvolupament iteratiu de la pàgina, el màrqueting i el disseny.
  %p Per últim, s’especiﬁca el tipus de contracte realitzat i la forma de pagament d’aquest. S’especiﬁca el concepte de propietat del codi realitzat per Itnig i s’explicita les formes de contacte.
  %h2 Descripció general del producte
  %p
    Es tracta d'un producte web integral ofert segons el nostre
    = succeed "." do
      %strong Pla Bàsic
    Entenem per integral el fet que comprèn els serveis  i necessitats accessories que acompanyen la presència a Internet. Són els següents:
  %ul
    %li El disseny personalitzat a mida
    %li L'enginyeria de software i de sistemes que hi ha darrere la creació de la pàgina
    %li El manteniment tècnic de la pàgina
    %li El monitoratge, seguiment i promoció en el seu mercat a la Xarxa.
    %li Lloguer Màquines on s'allotja la pàgina
    %li Lloguer domini
  %p El seguiment de la pàgina és permanent. Es vetllarà perquè s'ofereixi la informació adequada, fàcilment trobable pels usuaris i comprovarem periòdicament que aquests realment hi arriben. Si quelcom falla, l'assessorem per modificar i actualitzar els seus continguts de forma que tinguin més sortida.
  %h2 Tecnologia
  %p
    La tecnologia emprada és
    = succeed "." do
      %strong Ruby on Rails
    Es tracta d'un dels frameworks de programació web més potents del món que treballa sobre el llenguatge Ruby. És una tecnologia lliure i oberta, amb una enorme comunitat que l'empara. Twitter.com, Basecamphq.com, Yellowpages.com i Github.com són només alguns exemples d’aplicacions web líders que usen aquesta tecnologia. Itnig és pionera a Espanya en l'ús d'aquesta tecnologia. Dissenyem les interfícies de les nostres aplicacions usant principalment l’entorn de treball
    %strong jQuery
    de Javascript. El sistema gestor de base de dades emprat serà
    = succeed "." do
      %strong MySQL
.page.shadow
  .headnote
    %div{:style => "float:right"}> 2
    Projecte #{@project}
  %h2 Servidors
  %p
    Els nostres servidors privats virtuals estan contractats a
    %strong Linode
    Europa. Linode és una de les empreses que ofereix infraestructura per executar aplicacions Ruby més
    %strong ràpides
    del món. Els temps de resposta dels llocs allotjats són dramàticament més petits que la seva competència. A més, el fet de situar infraestructura a Europa en comptes de centres de dades en altres continents ens beneficia perquè guanyem sobre un 30% de rapidesa en cada petició per proximitat geogràfica.
  %p El nostre manteniment es concentra en que el servidor mai es quedi curt en respondre el volum de visites que sigui a la pàgina. Augmentem la contractació de memòria RAM o capacitat de transferència de les nostres màquines quan així ho considerem necessari
  %h2 Disseny
  %p
    Som especialistes en el
    = succeed "." do
      %strong disseny funcional, usable i accessible
    El nostre dissenyador revisarà els dissenys dels nostres clients per comprovar que siguin funcionals, usables i accessibles. De la mateixa manera, optimitzarem l’estructura de la pàgina de cara als motors de cerca. Si la mètrica d'usuari indica que alguna part del disseny no està orientant bé als usuaris, es modificarà immediatament.
  %p
    Els estàndards seguits són de moment
    = succeed "." do
      %strong XHTML 1.0 i CSS2
    Estem a l'espera que evolucioni definitivament l'estàndard en tots els navegadors i puguem migrar les aplicacions a
    = succeed "." do
      %strong HTML5 i CSS3
  %h2 Marketing online
  %p
    %strong 1.
    Posar i renovar periòdicament anuncis en portals d’anuncis generalistes: És crearan i renovaran anuncis en directoris com Pàgines Amarillas o Classificats que permetin anunciar la web i els serveis de la nostres clients. La majoria d’aquests portals no admeten enllaços, però els que ho permetin serà important aconseguir-los.
  %p
    %strong 2.
    Registrar la pàgina en directoris web generalistes: És registrarà el lloc web, amb informació corporativa i personal als directoris generalistes més importants, com DMOZ, Vulka o Hotfrog, entre d'altres. Els directoris que ho permetin s’afegirà informació gràfica i un enllaç.
  %p
    %strong 3.
    Posar i renovar anuncis en directoris i portals específics del sector: La missió d’aquest punt es aconseguir enllaços de portals, fòrums, pàgines d’anuncis relacionades amb el lloc web, o sigui, del sector del nostre client. Aquests anuncis en pàgines relacionades s'hauran d'anar controlant per saber el nombre de visites, i en el cas que el portal ho permeti, quina valoració en fan els usuaris, o si han deixat comentaris positius o negatius respondre amb rapidesa sobre la pàgina del nostre client.
  %p
    %strong 4.
    Assessorament dels nous continguts creats: Al llarg de la vida del lloc es pot anar actualitzant la informació relativa a projectes concrets, serveis o informació personal. Si es produeixen events concrets, podem usar-los per promocionar-los individualment per mitjà de pàgines dedicades que contribueixen a enrquir el contingut de la pàgina.  En el cas d’anuncis o directoris on existeix la possibilitat de mostrar imatges, s’aniran actualitzant en funció de la seva importància i qualitat.  A nivell d’optimització interna, és crearan les metadades (keywords, description, geotags, etc.) adients per posicionar adequadament tots els continguts nous.
.page.shadow
  .headnote
    %div{:style => "float:right"}> 3
    Projecte #{@project}
  %p
    %strong 5.
    Medir les visites i les respostes que tenen les pàgines i enviar-li informes mensuals al client. Mensualment (aproximadament el dia 30 de cada mes) el client rebrà els informes amb les conclusions generals. L’objectiu dels informes és:
  %p
    %strong 6.
    Extreure totes les dades possibles que ajudin a fer-se una idea global de l’estat del lloc web.
  %p
    %strong 7.
    Saber si els canvis que es van aplicant tenen èxit, per tal de perfeccionar les keywords, ajustar continguts, valorar les noves imatges de la galeria, etc. Un cop extretes les dades, és crearan unes conclusions que facilitin la comprensió dels diferents informes, que tot i ser molt visuals, presenten dificultats alhora de comprendre l’evolució  i el funcionament del lloc web.
  %h2 Contracte
  %p
    Aquest producte s'ofereix per mitjà del nostre
    = succeed "," do
      %strong Pla Bàsic
    que inclou tots els serveis anteriorment descrits però per una pàgina de dimensions reduides, com és el seu cas. Entenem com a pàgina de dimensions reduides aquella que no preveu abundant creació de contingut o que no permet la venta directa a la Xarxa. Evidentment, es pot canviar en qualsevol moment i ampliar les funcionalitats i serveis oferts a un pla més avançat.
  %p
    El contracte té un preu mensual de
    %strong 65€ + IVA
    al mes, la forma de pagament és personalitzable, tot i que recomanem domiciliació bancaria o pagament per blocs de 6 mesos. També és possible pagar en efectiu.
  %p
    Si no obté els resultats esperats i vol rescindir el contracte, pot fer-ho sense compromís passats 6 mesos des de la data de contractació. El codi de la seva pàgina és públic (pot veure el nostre repositori de codi a
    = succeed ")" do
      %a{:href => "http://github.com/itnig"} http://github.com/itnig
    i vostè és lliure de reutilitzar-lo en un futur de la manera que vulgui. Té a la seva disposició el nostre pla d'allotjament + domini per ex-clients, que té un cost de
    %em 20€/mes + IVA
    i contempla el manteniment de la web a la Xarxa (domini i allotjament), però no inclou cap servei de seguiment, promoció, manteniment o re-disseny de la web. Ara bé, li dóna la oportunitat de tornar a contractar un pla bàsic en el moment que ho cregui oportú.
  %h2 Forma de pagament
  %p
    El contracte d’un Pla Bàsic d’Itnig té un preu mensual de 65€ + IVA (18%)  al mes, la forma de pagament és adaptable, tot i que recomanem domiciliació bancaria o pagament per blocs de 6 mesos. A la factura es reté un 7% d’IRPF, per tant el preu final és 65 + 11,7 (IVA) - 4,55 (Retenció IRPF) =
    = succeed "." do
      %strong 72,15 € / mes
  %p
    Tanmateix,
    = succeed ":" do
      %u els primers sis mesos s’han d’abonar al principi amb un sol pagament
  %p
    L'import inicial exacte és: Pla bàsic x 6 mesos: 390€ + 70,2€ (IVA) - 27,3€ (Ret IRPF) =
    %strong 432,9€
  %p El compte on realitzar els pagaments és el següent:
  .wrapped_box
    %p
      %strong Titular
      Itnig Solutions
      %br/
      %strong Entitat
      todo
      %br/
      %strong Compte
      todo
  %p Tan bon punt rebem el primer pagament li enviarem la factura per correu electrònic i començarem a treballar en el projecte.
.page.shadow
  .headnote
    %div{:style => "float:right"}> 3
    Projecte #{@project}
  %h2 Contacte amb Itnig
  %p Pot contactar amb nosaltres sempre que vulgui dins dels nostres horaris de treball. El nostre mitjà de contacte preferit és el correu electrònic, tant aviat com tinguem disponibilitat respondrem el seu problema.
  %p Les nostres adreces són:
  .wrapped_box
    %p
      %strong info@itnig.net
      \- Per qüestions generals
      %br/
      %strong design@itnig.net
      \- Per qüestions de disseny
      %br/
      %strong it@itnig.net
      \- Per qüestions d'enginyeria
      %br/
  %p
    Horari de treball a Itnig:
    %strong De 10 a 14h del matí i de 16 a 20h de la tarda.
  %p
    També pot parlar telefònicament amb el
    %strong Sergi
    al
    = succeed "." do
      %strong 668 819 184
.last_page.page.shadow
  .headnote
    %div{:style => "float:right"}> 4
    Projecte #{@project}
  %h1 Contracte de serveis
  %br/
  %br/
  %p
    Per una part
    %strong= @client.name
    amb DNI/CIF #{raw @client.nif.blank? ? "....................................." : "<strong>" + @client.nif + "</strong>"} representant la part del client i per l’altra part
    %strong Itnig solutions
    amb DNI
    %strong todo
    representant la part de prestador del servei.
  %h3.center CLÀUSULES
  %p PRIMERA. Aquest contracte és vigent a partir del moment en que ambdues parts el signen i té una validesa mínima de sis mesos.
  %p SEGONA. Totes les pàgines del document anterior han estat acceptades i signades per ambdues parts i formen part del present contracte.
  %p TERCERA. El prestador de serveis es compromet a vetllar per l’interès de negoci del client i no actuarà en cap cas de forma negligent, amb mala fe o es sotmetrà a coacció o pressió de terceres parts.
  %p
    QUARTA. El client autoritza a carregar al seu compte la quantitat corresponent al
    %strong
      Pla #{t(@project.type).capitalize!}
    que ha contractat.
  %h3.center SERVEIS
  %p
    CINQUENA. Els serveis oferts que inclouen construcció de l’aplicació web, disseny, allotjament, domini i promoció a Internet en l’intensitat descrita al
    %strong
      Pla #{t(@project.type).capitalize!}
    han estat descrits en l’anterior document i han estat acceptats i signats per ambdues parts.
  %h3.center MODIFICACIONS
  %p SISENA. Es podran fer modificacions d’aquest contracte en qualsevol moment. Tanmateix, aquestes seran especificades i negociades entre ambdues parts i resultaran en un document signat que s’annexarà a aquest.
  %h3.center COMPLIMENT
  %p SETENA. Les parts executaran i vetllaran perquè es compleixi tot allò especificat en el document.
  %br/
  %br/
  %p
    Signat a
    %strong Barcelona
    , el dia
    %strong= I18n.l(Date.today, :format => :long)
  %br/
  %div{:style => "float:right;margin-right:12em"}
    %p
      %u El Client
  %p{:style => "margin-left:5em;"}
    %u El Prestador

app/views/projects/_form.html.haml
= simple_form_for @project, :html => { :class => :form } do |f|
  = f.input :name, :label => "Nom"

  = f.input :ref, :label => "Referència"

  = f.association :project_type, :include_blank => false, :label => "Tipus de projecte"

  = f.input :state, :collection => Project::STATES_LIST, :include_blank => false, :label => "Estat del projecte"

  = f.input :starting_date, :as => :string, :input_html => {:class => "datepicker", :value => ( @project.starting_date || Date.today )}, :label => "Data d'inici"

  %p Atenció, el camp d'informació serà públic, ha d'estar escrit en la llengua del client i formarà part del contracte, sigueu explícit i formal.

  = f.wmd_tag(:info)

  %h3 Gestiona els usuaris del projecte

  = f.association :employees, :label => "Participants al projecte", :include_blank => false

  = f.association :manager, :collection => Employee.all, :label => "Manager", :include_blank => false

  = f.submit :class => "button"

app/views/projects/_project_stats.html.haml
#stats.span-24
  .span-15.column.first
    %table
      %tr.odd
        %td
          %b Manager:
        %td= @project.manager
      %tr.even
        %td
          %b Data d'inici:
        %td
          = (@project.starting_date ? I18n.l(@project.starting_date.to_date) : "(undefined)")
      %tr.odd
        %td
          %b Client:
        %td= link_to @project.client, @project.client
      %tr.even
        %td
          %b Milestones pendents:
        %td= @project.milestones.marked_uncompleted.count.to_s + "/" + @project.milestones.count.to_s
      %tr.odd
        %td
          %b Tasques pendents:
        %td= @project.tasks.uncompleted.count.to_s + "/" + @project.tasks.count.to_s
      %tr.even
        %td
          %b Missatges:
        %td= h @project.messages.count.to_s
      %tr.odd
        %td
          %b Hores de treball previstes:
        %td
          = @project.calculate_total_hours.to_s
          h
      %tr.even
        %td
          %b Hores de treball realitzades:
        %td
          = @project.completed_hours.to_s
          h
      %tr.odd
        %td
          %b Contracte
        %td= link_to @project.contract_filename, @project.contract_get_file_url if @project.contract?
      - if @project.project_type
        %tr.even
          %td
            %b Tipus de projecte:
          %td
            %b= t("#{@project.project_type}")
        - if @project.project_type.name == "basic"
          %tr.odd
            %td
              %b Prototip de contracte:
            %td
              = link_to "CAT", contract_project_path(@project, :lang => "ca")
              = link_to "ESP", contract_project_path(@project, :lang => "es")
    %br/
  .span-8.column.last
    %p
      %b Persones assignades al projecte:
    - @project.employees.each do |user|
      .prepend-1.span-12
        .span-5.first.colborder.column
          = raw gravatar_for(user, :size => 35)
        .span-15.column.last
          = link_to user.name, user
          - if @project.manager == user
            = " (PM)"
  .span-24
    .prepend-2.span-10.column.first
      %span{:style => "float:left;"}= link_to "<<", :date =>  (@date - 19).to_s
      %span{:style => "float:right;margin-right:80px;"}= link_to ">>", :date => (@date + 19).to_s
    #project_activity.span-12.column.first
    #group_hours.span-10.column.last

app/views/projects/contract.html.haml
- title "Document #{@project.client.name}"
#heading= link_to "Descarrega en PDF", contract_project_path(@contract, :lang => @lang, :format => :pdf)
- if @lang.blank?
  = render "contract_ca"
- else
  = render (@lang.to_s == "es" ?  "contract_es" : "contract_ca")

app/views/projects/contract.pdf.haml
%html
  %head
    %title
      Document #{@client.name}
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}/
    <link rel="stylesheet" type"text/css" href="#{root_url}stylesheets/pageable_print.css" media="screen">
  %body
    - if @lang.blank?
      = render "contract_ca"
    - else
      = render :partial => (@lang.to_s == "es" ?  "contract_es" : "contract_ca").to_s + ".html"

app/views/projects/edit.html.haml
- title "Modifica Project"
= link_to image_tag("deleteicon.png"), @project, :confirm => 'COMPTE! Perdràs tota la informació del projecte. Vols prendre aquesta decisió?', :method => :delete, :class => "button right"
%h1 Modifica Projecte
.standard-form
  = render "form"

app/views/projects/get_roi.js.erb
$.facebox("<%= number_to_currency(@info['itnig_part']) %>");

app/views/projects/index.html.haml
- title "Projects"
- if can? :create, Project
  = link_to "+ Nou projecte", new_project_path, :class => "button right"
- if can? :read, ProjectType
  = link_to 'Tipus projecte', project_types_path, :class => "button right"

%h1 Llista de projectes
%table.listing_projects
  %tr
    %th Projecte
    %th PM
    %th Refèrencia
    %th Tipus
    %th Estat
    %th.last Manager Actions
  - @projects.each do |project|
    - opts = []
    - opts << "managed" if project.manager == current_user
    %tr{:class => opts.join(" "), :style => "color: #{project.to_color};"}
      %td= link_to project.name, project
      %td= project.manager
      %td= project_link(project, :label => :ref)
      %td
        - if project.project_type
          = t("#{project.project_type}")
      %td= project.state
      %td
        - if can? :update, project
          = link_to image_tag("editicon.png"), edit_project_path(project), :class => "button"

= will_paginate @events, :previous_label => "&laquo; Anterior", :next_label => "Següent &raquo;"

app/views/projects/list_events.html.haml
%table.overview
  %tr
  = render :partial => 'events/event', :collection => @events
= will_paginate @events, :previous_label => "&laquo; Anterior", :next_label => "Següent &raquo;"
= javascript_tag "formatLinkForPaginationURL();"

app/views/projects/new.html.haml
- title "Nou projecte"
%h1 Nou Projecte
.standard-form
  = render "form"

app/views/projects/show.html.haml
- title "Projecte " + @project.ref
%h1 Vista general de #{@project}

#project-show
  .project-stats
    %h2 Estadístiques del projecte
    .first-table
      %table
        %tr
          %td Nom del projecte
          %td= @project.name
        %tr
          %td Referència projecte
          %td ##{@project.ref}
        %tr
          %td Número de projecte
          %td= @project.id
        %tr
          %td Project Manager
          %td= link_to @project.manager, @project.manager
        %tr
          %td Data d'inici
          %td= @project.created_at.strftime("%d/%m/%Y") + " (#{pretty_date @project.created_at})"
        %tr
          %td Estat de prioritat
          %td
            - if can? :update, @project
              = best_in_place @project, :status, :type => :select, :collection => Project::STATUS_LIST
            - else
              = @project.status

    .second-table
      %table
        %tr
          %td Hores completades / Hores totals
          %td #{@project.completed_hours}h / #{@project.calculate_total_hours}h
        %tr
          %td Pròxima fita
          %td
            - mile = @project.milestones.upcoming.first
            - unless mile.blank?
              = link_to mile, project_milestone_path(@project, mile)
              = mile.friendly_date
            - else
              No n'hi ha
        %tr
          %td Fites completes / Fites pendents
          %td= link_to "#{@project.milestones.marked_completed.size} / #{@project.milestones.marked_uncompleted.size} milestones", project_milestones_path(@project)
        %tr
          %td Tasques completes / Tasques pendents
          %td= link_to "#{@project.tasks.completed.size} / #{@project.tasks.uncompleted.size} tasques", project_task_lists_path(@project)
        %tr
          %td Missatges escrits
          %td= link_to pluralize(@project.messages.size, "missatge"), project_messages_path(@project)
        %tr
          %td Documents adjunts
          %td= link_to pluralize(@project.attachments.size, "documents"), project_attachments_path(@project)
    .clearboth
  .one-half
    %h2 Treballadors del projecte (#{@project.employees.size})
    .project-members
      - @project.employees.each do |e|
        - klass = @project.manager == e ? "pm" : ""
        = link_to gravatar_for(e, :size => 50), e, :class => klass
  .one-half
    = link_to "Històric", "#status-history", :rel => "facebox", :class => "button right"
    %h2 Status del projecte
    .project-status
      - if can? :update, @project
        = best_in_place @project, :status_description, :type => :textarea, :activator => ".project-status"
      - else
        = @project.status_description
  .clearboth
  %h2 Descripció del projecte
  .project-description
    - if @project.info
      = raw markdown @project.info

  = render "shared/feeds"

  #status-history{:style => "display:none"}
    %h1 Historic de l'estat del projecte
    - foo = @project.previous_version
    - 10.times do
      - unless foo.nil?
        %p
          = "#{pretty_date foo.version.created_at}: "
          %b= foo.status_description.blank? ? "Buit" : foo.status_description
          %em= "per #{foo.version.whodunnit}"
        - foo = foo.previous_version