config/routes.rb
Intranet::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "user_sessions"}

  match "overview/list", :to => "overview#list"
  match "dashboard", :to => "overview#dashboard", :as => :dashboard

  resources :employees

  # Despert
  # ================================================================
  resources :groups
  resources :comments, :only => :destroy

  resources :project_types

  resources :projects, :only => :index
  resources :projects, :path => "", :except => :index do
    collection do
      get :list
    end

    resources :attachments

    resources :messages do
      collection do
        get :list
      end
    end

    resources :milestones do
      member do
        get :toggle
      end
    end

    resources :task_lists do
      resources :tasks, :only => :create

      collection do
        post :reorder_task
      end

      member do
        post :toggle_archive
        get :completed_tasks
      end
    end

    resources :tasks do
      member do
        get :toggle
        get :archive_toggle
        get :list_events
      end
    end
  end

  resources :tasks, :only => :none do
    resources :comments, :only => :create
  end

  resources :milestones, :only => :none do
    resources :comments, :only => :create

    collection do
      get :overview
    end
  end

  resources :messages, :only => :none do
    resources :comments, :only => :create
  end


  root :to => "overview#index"
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  fire_events :background => :project, :context => :project
  has_paper_trail :only => [:hours, :description], :meta => {:concept => :concept}

  has_many :tasks, :order => 'position ASC, completed_at DESC', :dependent => :destroy
  has_many :events, :as => :subject, :dependent => :destroy

  belongs_to :milestone
  belongs_to :group
  belongs_to :project

  validates_presence_of :name
  validates_presence_of :project
  validate :all_completed_tasks_when_archived

  attr_accessor :concept

  before_destroy :prevent_unassigned_deletion
  validate :concept_of_change_missing

  scope :archived, where(:archived => true)
  scope :unarchived, where(:archived => false)

  def total_hours
    tasks.map{|x| x.duration}.sum
  end

  def completed_hours
    tasks.completed.map{|x| x.duration}.sum
  end

  def completed_tasks_done
    tasks.completed.count
  end

  def to_s
    name
  end

  def toggle_archive
    self.archived = !archived
  end

  def increment_positions_from(position)
    tasks.where(Task.arel_table[:position].gt(position)).each do |t|
      t.position += 1
      t.save!
    end
  end

private
  def prevent_unassigned_deletion
    errors.add(:base, "No es pot esborrar la llista unassigned") if name == "unassigned"
  end

  def all_completed_tasks_when_archived
    errors.add(:base, "No pots arxivar-la si encara té tasques pendents") if archived? && tasks.uncompleted.any?
  end

  def concept_of_change_missing
    errors.add(:base, "Has d'explicar la raó dels canvis") if hours_changed? && concept.blank?
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  load_resource :project, :find_by => :ref
  authorize_resource :project
  load_and_authorize_resource :task_list, :through => :project, :except => [:reorder_task, :completed_tasks]

  layout 'project'

  def index
    t = TaskList.arel_table
    @unassigned = @task_lists.where(:name => "unassigned").first
    @archived_task_lists = @task_lists.archived.uniq
    @task_lists = @task_lists.unarchived.includes([ { :tasks => [:employee, :author] }, :group, :milestone ]).where(t[:name].not_eq("unassigned")).uniq

    @task_lists.sort! do |a,b|
      if a.milestone.nil? && b.milestone.nil?
        a.updated_at <=> b.updated_at
      elsif a.milestone.present? && b.milestone.present?
        a.milestone.finishes_at <=> b.milestone.finishes_at
      else
        a.milestone ? -1 : 1
      end
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @closed_tasks = @task_list.tasks.closed
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task_list }
      format.js
    end
  end

  def new
    @milestone_id = params[:milestone_id] if params[:milestone_id]
    render :layout => "no-layout"
  end

  def create
    respond_to do |format|
      if @task_list.save
        flash[:notice] = "Llista de tasques creada."
        format.html { redirect_to project_task_lists_path(@project) }
        format.xml  { render :xml => @task_list, :status => :created, :location => @task_list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task_list.update_attributes(params[:task_list])
        flash[:notice] = "Llista de tasques actualitzada correctament."
        format.html { redirect_to [@project, @task_list] }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @task_list.destroy

    flash[:notice] = "Llista de tasques destruida correctament."

    respond_to do |format|
       format.html { redirect_to project_task_lists_path(@project) }
     end
  end

  def toggle_archive
    @task_list.toggle_archive

    respond_to do |format|
      if @task_list.save
        format.html {redirect_to project_task_lists_path(@task_list.project)}
      else
        format.html { redirect_to request.env["HTTP_REFERER"], :alert => @task_list.errors.full_messages }
      end
    end
  end

  def reorder_task
    @task = Task.find params[:from]
    authorize! :reorder, @task

    ## This avoids to process a call that shouldn't be done from the sortable
    ## jquery setup, but I was unable to avoided otherwise.
    if params[:from_task_list] == params[:to_task_list] && params[:cuca] != "nohay"
      render :status => :unprocessable_entity, :nothing => true
      return
    end

    @to_task_list = TaskList.find params[:to_task_list]
    @to_task = Task.find_by_id params[:to]

    @task.move_to(@to_task_list, @to_task)

    respond_to do |format|
      @task.save

      format.js
    end
  end

  def completed_tasks
    @task_list = @project.task_lists.find params[:id]
    authorize! :read, @task_list

    @tasks = @task_list.tasks.completed

    respond_to do |format|
      format.js
    end
  end
end

app/views/task_lists/_form.html.haml
- unless f.error(:base).blank?
  .notice= f.error :base

= f.label :name, "Nom", :class => :label
= f.text_field :name, :class => 'text_field'

- if @milestone_id.blank?
  = f.label :milestone_id, "Milestone", :class => :label
  = f.select 'milestone_id', @project.milestones.marked_uncompleted.collect { |m| [m.name, m.id] }, { :include_blank => "Cap"}
- else
  = f.hidden_field :milestone_id, :value => @milestone_id

= f.label :group_id, "Grup que desenvoluparà les tasques", :class => :label
= f.select 'group_id', Group.all.collect { |m| [m.ref, m.id] }, { :include_blank => "Cap"}

.right COMPTE! Les hores planificades cal pensar-les bé i no s'haurien de modificar mai més.
= f.label :hours, "Hores previstes", :class => :label
= f.text_field :hours, :class => 'text_field'

.right El camp de descripció ha de comprendre tot el que caldrà fer sobre aquella tasca i no es podrà modificar.
= f.label :description, "Descripció", :class => :label
= f.text_area :description, :class => 'text_field', :style => "height: 4em;"

- unless @task_list.new_record?
  #change-concept{:style => "display:none"}
    = f.label :concept, "Per què modifiques aquesta llista de tasques?"
    = f.text_area :concept, :class => 'text_field', :style => "height: 2em;"

.center= f.submit :class => "button"


- content_for :custom_js do
  :javascript
    $(document).ready(function() {
      var show_concept = function() {
        $("#change-concept").fadeIn();
        $("#task_list_concept").focus();
      }
      $("#task_list_hours").change(function(){show_concept()});
      $("#task_list_description").change(function(){show_concept()});
    });

app/views/task_lists/_task_list.html.haml
.task_list{:id => "full_task_list_#{task_list.id}", :style => "background-color:##{task_list.group ? soft_color(task_list.group.color) : "FEFEFF"};"}
  - if can? :destroy, task_list
    = link_to image_tag("deleteicon.png"), project_task_list_path(@project, task_list), :confirm => 'Segur?', :method => :delete, :class => "button right"
  - if can? :update, task_list
    = link_to image_tag("editicon.png"), edit_project_task_list_path(@project, task_list), :class => "button right"
    - icon = task_list.archived? ? "archive.png" : "emptyfolder.png"
    = link_to image_tag(icon), toggle_archive_project_task_list_path(@project, task_list), :class => "button right", :method => :post, :title => "Arxivar/Desarxivar"
  %h2
    = link_to task_list.name, [@project, task_list]
    - if task_list.archived?
      [Arxivat #{pretty_date task_list.updated_at}]
  - if task_list.archived? && action_name != "show"
    Milestone:
    = task_list.milestone.blank? ? "Cap" : link_to(task_list.milestone.name, [task_list.project, task_list.milestone])
    |
    Tasques: ##{task_list.tasks.size} | Hores planificades #{task_list.hours} h | Hores efectuades #{task_list.total_hours} h
  - else
    .task-data
      .right
        - unless task_list.hours.blank?
          Hores planificades:
          %b #{task_list.hours} h
          |
        Hores efectuades:
        %b #{task_list.total_hours} h
      - unless task_list.description.blank?
        .left= link_to image_tag("lupa.png"), "#task-list-#{task_list.id}-description", :rel => "facebox"
        %div{:id => "task-list-#{task_list.id}-description", :style => "display:none;"}
          %h1 Descripció de la feina
          %span{:style => "font-size:1.2em;"}= task_list.description
      - if task_list.group
        .left= image_tag("group.png")
        .left= link_to task_list.group.name, task_list.group if task_list.group
      - if task_list.milestone
        .left= image_tag("calendar.png")
        .left
          = link_to task_list.milestone, [@project, task_list.milestone], :title => task_list.milestone
          = task_list.milestone.friendly_date
    .task_list_items_uncompleted{:id => "task_list_uncompleted_#{task_list.id}", :"data-id" => task_list.id}
      = render task_list.tasks.active.select{|x| !x.completed?}, :task_list => task_list
    .separator{:style => "height:.5em"}
    - unless action_name == "show"
      .right
        +
        %span{:id => "comptasks_#{task_list.id}"}= task_list.completed_tasks_done
        = link_to "tasques completades", completed_tasks_project_task_list_path(@project, task_list), :remote => true, :id => "completed_link_#{task_list.id}"
    .completed_tasks{:style => "#{action_name == 'show' ? '' : 'display:none'}"}
      %h4 Tasques completades
      .task_list_items_completed{:id => "task_list_completed_#{task_list.id}"}
        = render task_list.tasks.active.select{|x| x.completed?}, :task_list => task_list if action_name == "show"
      - if action_name == "show" && @closed_tasks && @closed_tasks.size > 0
        .right= link_to "Veure tasques tancades", "#closed-tasks", :id => "show-closed"
        #closed-tasks{:style => "display:none"}
          %h4 Tasques tancades
          = render @closed_tasks
    .separator
    .button.show_next_div{:id => "task_list_#{task_list.id}_add_text"}
      + Afegir tasca
    .add_item_form{:id => "task_list_#{task_list.id}_add_form", :style => "display:none;"}
      = form_for [@project, task_list, Task.new], :remote => true,  :html => { :class => :form, :id => "task_list_#{task_list.id}_new_task" }, :index => task_list.id do |f|
        = render "tasks/form", :f => f, :task_list => task_list

= content_for :custom_js do
  :javascript
    $(document).ready(function() {
      $("#show-closed").click(function() {
        $("#closed-tasks").fadeIn();
      });
    });
    $('#task_list_uncompleted_#{task_list.id}').sortable({
      axis: 'y',
      cursor: 'crosshair',
      connectWith: '.task_list_items_uncompleted',
      opacity: 0.8,
      scroll: true,
      update: function(event, ui){
        var res = ui.sender == null ? "nohay" : ui.sender.attr('data-id');
        $.ajax({
          type: 'post',
          data: '&from_task_list=#{task_list.id}' +
            '&to_task_list=' + ui.item.parent().attr('data-id') +
            '&from='+ui.item.attr("data_task") +
            '&to='+ui.item.prev().attr("data_task") +
            '&cuca='+res,

          dataType: 'script',
          url: '#{reorder_task_project_task_lists_path(@project)}'
        })
      }
    });

app/views/task_lists/_unassigned.html.haml
- tasks = unassigned.blank? ? [] : unassigned.tasks
-# = form_for [@project, Task.new] do |f|
-#   = f.text_field :title, :placeholder => "Nova tasca no assignada"
- if tasks.size < 1
  .separator
  %p.center No hi ha cap tasca a la llista
  .separator
- else
  - tasks.each do |t|
    .task= t.title

app/views/task_lists/completed_tasks.js.erb
if ($("#completed_link_<%= @task_list.id %>").hasClass("display"))
{
  $("#completed_link_<%= @task_list.id %>").removeClass("display");
  $("#full_task_list_<%= @task_list.id -%> .completed_tasks").fadeOut();
}
else
{
  $("#full_task_list_<%= @task_list.id -%> .completed_tasks").fadeIn();
  $("#completed_link_<%= @task_list.id %>").addClass("display");
  <% @tasks.each do |t| %>
    if (jQuery.isEmptyObject($("#task_item_<%= t.id %>")[0]))
    {
      $("#task_list_completed_<%=t.task_list.id.to_s%>").append("<%= raw escape_javascript(render t, :task_list => @task_list) %>");
    }
  <% end %>
}

app/views/task_lists/edit.html.haml
- title "Modifica Llista de Tasques"

%h1 Modifica Llista de Tasques
.standard-form
  = simple_form_for [@project, @task_list], :html => { :class => :form } do |f|
    = render :partial => "form", :locals => {:f => f}

app/views/task_lists/index.html.haml
- title "Llistes de tasques"
- if can? :create, @project.task_lists.new
  = link_to "+ Nova llista de tasques", new_project_task_list_path(@project), :class => "button right", :rel => "facebox"
%h1 Llistes de tasques

#task-lists
  .regular-task-lists
    = render @task_lists
    - if @archived_task_lists.size > 0
      .center= link_to "Llistes arxivades", "#archived-task-lists", :id => "show-archived", :class => "button"
      #archived-task-lists{:style => "display:none"}
        = render :partial => "task_list", :collection => @archived_task_lists
  .sidebar{:style => "#{@task_lists.size < 1 ? 'width:98%' : ''};"}
    %h3 Llistes de tasques (#{@task_lists.size})
    - @task_lists.each do |tl|
      .task-list-link{:style => "background-color:##{tl.group ? soft_color(tl.group.color) : "FEFEFF"};"}
        .right (#{tl.tasks.completed.size}/#{tl.tasks.size})
        = link_to image_tag("calendar.png"), [@project, tl.milestone], :title => tl.milestone.to_s unless tl.milestone.blank?
        = link_to tl.name, "#full_task_list_#{tl.id}"
      -# %h3 Tasques no assignades
      -# = render :partial => "unassigned", :locals => { :unassigned => @unassigned }

= content_for :custom_js do
  :javascript
    $(document).ready(function() {
      $("#show-archived").click(function() {
        $("#archived-task-lists").fadeIn();
      });
    });
    $(function() {
      var $sidebar   = $(".sidebar"),
          $window    = $(window),
          offset     = $sidebar.offset();
      $window.scroll(function() {
        if ($window.scrollTop() > offset.top) {
          $sidebar.css("position", "fixed");
          $sidebar.css("top", ".3em");
        } else {
          $sidebar.css("position", "absolute");
          $sidebar.css("top", "20em");
        }
      });
    });

app/views/task_lists/new.html.haml
- title "Nova llista de tasques"
%h1 Nova llista de tasques
.standard-form
  = simple_form_for [@project, @task_list], :html => { :class => :form } do |f|
    = render :partial => "form", :locals => {:f => f}

app/views/task_lists/show.html.haml
- title "Llista de tasques: " + @task_list.name

= render @task_list, :object => @task

%h3 Històric de canvis
.show-history
  %table
    - foo = @task_list.previous_version
    %tr
      %th Data
      %th Concepte
      %th Hores planificades
      %th Descripció
      %th Autor modificació
    - 10.times do
      - unless foo.nil?
        - unless foo.version.concept.blank?
          %tr
            %td= pretty_date foo.version.created_at
            %td= foo.version.concept
            %td= "#{foo.hours} h"
            %td= foo.description
            %td= foo.version.whodunnit
        - foo = foo.previous_version